
language: java

jdk:
   - openjdk8
 
 script:
    - echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache
    
    cat $HOME/m2/settings.xml
